import { BaseEntity } from '../../../shared/infrastructure/base-entity';

/**
 * Represents a telemetry record generated by a device.
 */
export class TelemetryPoint implements BaseEntity {
  constructor(props: {
    id: string;
    deviceId: string;
    recordedAt: Date;
    lat: number;
    lng: number;
    speed: number;
    signalQuality: number;
  }) {
    this._id = props.id;
    this._deviceId = props.deviceId;
    this._recordedAt = props.recordedAt;
    this._lat = props.lat;
    this._lng = props.lng;
    this._speed = props.speed;
    this._signalQuality = props.signalQuality;
  }

  private _id: string;

  get id(): string {
    return this._id;
  }

  set id(value: string) {
    this._id = value;
  }

  private _deviceId: string;

  get deviceId(): string {
    return this._deviceId;
  }

  set deviceId(value: string) {
    this._deviceId = value;
  }

  private _recordedAt: Date;

  get recordedAt(): Date {
    return this._recordedAt;
  }

  set recordedAt(value: Date) {
    this._recordedAt = value;
  }

  private _lat: number;

  get lat(): number {
    return this._lat;
  }

  set lat(value: number) {
    this._lat = value;
  }

  private _lng: number;

  get lng(): number {
    return this._lng;
  }

  set lng(value: number) {
    this._lng = value;
  }

  private _speed: number;

  get speed(): number {
    return this._speed;
  }

  set speed(value: number) {
    this._speed = value;
  }

  private _signalQuality: number;

  get signalQuality(): number {
    return this._signalQuality;
  }

  set signalQuality(value: number) {
    this._signalQuality = value;
  }
}
